### PR TITLE
Deletion and tests

### PR DESCRIPTION
**Pull request by richardcase**

### CODE REVIEW

**Comment by nab-gha** [comment]
This is good stuff we should merge ASAP

**Comment by richardcase** [comment]
More tests are needed but this is a start

**Review by nab-gha — CHANGES_REQUESTED** [review]
Look good but trying to run restore against this fails

python3 dr restore --clustername cluster2 --bucket bank-apps-backup --log-level DEBUG
2020-02-10 18:39:27,894 restore.restore:23 - restore_command() INFO - starting restore
2020-02-10 18:39:27,895 restore.restore:26 - restore_command() DEBUG - using temporary directory: /tmp
2020-02-10 18:39:27,925 botocore.credentials:1073 - load() INFO - Found credentials in environment variables.
2020-02-10 18:39:29,136 restore.strategy:41 - start_namespace() DEBUG - working file for namespace bank-app1 is /tmp/bank-app1.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "dr/__main__.py", line 20, in <module>
    cli(auto_envvar_prefix='DR')
  File "/home/pcarlton/src/github.com/paulcarlton-ww/k8s-dr-utils/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/pcarlton/src/github.com/paulcarlton-ww/k8s-dr-utils/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/pcarlton/src/github.com/paulcarlton-ww/k8s-dr-utils/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pcarlton/src/github.com/paulcarlton-ww/k8s-dr-utils/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pcarlton/src/github.com/paulcarlton-ww/k8s-dr-utils/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "dr/restore/restore.py", line 31, in restore_command
    restore.restore_namespaces(clusterName=clustername, namespacesToRestore=namespace)
  File "/home/pcarlton/src/github.com/paulcarlton-ww/k8s-dr-utils/utilslib/library.py", line 125, in wrapper
    return func(*args, **kwargs)
  File "/home/pcarlton/src/github.com/paulcarlton-ww/k8s-dr-utils/utilslib/dr.py", line 446, in restore_namespaces
    for key in self.get_bucket_keys(prefix):
  File "/home/pcarlton/src/github.com/paulcarlton-ww/k8s-dr-utils/utilslib/library.py", line 125, in wrapper
    return func(*args, **kwargs)
  File "/home/pcarlton/src/github.com/paulcarlton-ww/k8s-dr-utils/utilslib/library.py", line 106, in wrapper
    raise e
  File "/home/pcarlton/src/github.com/paulcarlton-ww/k8s-dr-utils/utilslib/library.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "/home/pcarlton/src/github.com/paulcarlton-ww/k8s-dr-utils/utilslib/dr.py", line 155, in get_bucket_keys
    return list(map(lambda i: i['Key'], response['Contents']))
KeyError: 'Contents'

Can we fix that before merging?

**Comment by richardcase** [comment]
Yeah restore is probably broken due to some changes. Will fix and add tests first thing in the morning

**Review by nab-gha — APPROVED** [review]

**Comment by nab-gha** [comment]
restore works now, merge this if you want

**Pull request merged**
